### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by cornelinux**
Credits go to Nicolas B.

### CODE REVIEW

**Review by nilsbehlen — COMMENTED** [review]
i do not know if there is anything else that needs to be done to use this translation. Maybe @timosturm can check it out aswell

**Comment by timosturm** [comment]
The translations look fine, some changes must still be made to the code to make the language available. I will do this myself later.

**Comment by timosturm** [comment]
This works fine now, except for one thing: I forgot that the user guide has to be translated also. This should be done before merging this into the master.

**Comment by timosturm** [comment]
Should we / are we allowed to credit the person in the changelog?

**Pull request merged**
